# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_populate_device_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestate',
            name='id',
        ),
        migrations.AlterField(
            model_name='devicestate',
            name='state',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
