# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_state_primary_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('device_name', 'location')]),
        ),
    ]
