# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20160405_1453'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('device_name', 'location'), ('device_name', 'serial_num')]),
        ),
    ]
