# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20160405_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ip_addr',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_num',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('device_name', 'ip_addr'), ('device_name', 'location')]),
        ),
    ]
